name: Build Template (Manual)
on:
  workflow_dispatch: # This makes it manual only

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Compile
        run: python build.py
      - uses: actions/upload-artifact@v4
        with:
          name: Premium-Blogger-Theme
          path: dist/theme.xml
